      PROGRAM HELLO2

c     A simple MPI program for testing.
 
      IMPLICIT NONE

      INCLUDE 'mpif.h'

      INTEGER IERROR
      INTEGER RANK
      INTEGER SIZE
      INTEGER RESULTLEN
      CHARACTER*(MPI_MAX_PROCESSOR_NAME) NAME
c      CHARACTER*(32) NAME

      CALL MPI_INIT(IERROR)

      CALL MPI_COMM_RANK(MPI_COMM_WORLD, RANK, IERROR)

      CALL MPI_COMM_SIZE(MPI_COMM_WORLD, SIZE, IERROR)

      CALL MPI_GET_PROCESSOR_NAME(NAME, RESULTLEN, IERROR)
      
      IF (RANK == 0) THEN      
c          WRITE (*,*) 'Major Rank ', RANK, 'Size ', SIZE, 'Name ', NAME
          MPI_SEND(NAME, MPI_MAX_PROCESSOR_NAME, MPI_CHAR, 0, RANK, MPI_COMM_WORLD, IERROR)

          MPI_GATHER(NAME, SENDCOUNT, MPI_CHAR, RECVBUF, RECVCOUNT, RECVTYPE, RANK, COMM, IERROR)
      ELSE
c          WRITE (*,*) 'Minor Rank ', RANK, 'Name ', NAME
          MPI_SEND(NAME, MPI_MAX_PROCESSOR_NAME, MPI_CHAR, 0, RANK, MPI_COMM_WORLD, IERROR)
      ENDIF

      CALL MPI_FINALIZE(IERROR)

      END PROGRAM HELLO2
