      PROGRAM HELLO2

c     A simple MPI program for testing.
 
      IMPLICIT NONE

      INCLUDE 'mpif.h'

      INTEGER IERROR
      INTEGER RANK
      INTEGER SIZE
      INTEGER RESULTLEN
      CHARACTER*(MPI_MAX_PROCESSOR_NAME) NAME
c      CHARACTER*(32) NAME
      CHARACTER*(MPI_MAX_PROCESSOR_NAME) NAMER
c      CHARACTER*(32) NAMER
      INTEGER I

      CALL MPI_INIT(IERROR)

      CALL MPI_COMM_RANK(MPI_COMM_WORLD, RANK, IERROR)

      CALL MPI_COMM_SIZE(MPI_COMM_WORLD, SIZE, IERROR)

      CALL MPI_GET_PROCESSOR_NAME(NAME, RESULTLEN, IERROR)
      
      IF (RANK == 0) THEN      
      WRITE (*,*) 'Major Rank ', RANK, 'Size ', SIZE, 'Name ', NAME
      DO 10 I = 1, SIZE - 1
      CALL MPI_RECV(NAMER, MPI_MAX_PROCESSOR_NAME, MPI_CHAR,
        0, RANK, MPI_COMM_WORLD, IERROR)
      WRITE (*,*) 'Minor Rank ', RANK, 'Name ', NAME
  10  CONTINUE
      ELSE
c      WRITE (*,*) 'Minor Rank ', RANK, 'Name ', NAME
      CALL MPI_SSEND(NAME, MPI_MAX_PROCESSOR_NAME, MPI_CHAR, 0,
        RANK, MPI_COMM_WORLD, IERROR)
      ENDIF

      CALL MPI_FINALIZE(IERROR)

      END PROGRAM HELLO2
